project:
    type: website
    output-dir: ../docs

website:
    title: "A Terminal Coding Experience"
    navbar:
        left:
            - href: index.qmd
              text: Home
            - href: terminals.qmd
              text: Terminals
            - href: prework.qmd
              text: Pre-work
            - href: software.qmd
              text: Software
            - href: finalsteps.qmd
              text: Final Steps
            - href: vscode.qmd
              text: vscode
            - href: utils.qmd
              text: Utilities

format:
    html:
        theme: cosmo
        css: styles.css
        toc: true
        code-copy: true
