project:
  type: website
  output-dir: ../docs

website:
  title: "Getting Started with Quarto and Python"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



